-- ============================================================================
-- VibeTable — Complete MySQL 8.0+ schema
-- ----------------------------------------------------------------------------
-- This is the canonical production schema. It is executed verbatim by the
-- TypeORM migration `1700000000000-InitialSchema` (see backend/src/database/
-- migrations). All foreign keys, indexes and constraints are defined here;
-- the TypeORM entities mirror this file 1:1 for typed data access.
--
-- Charset: utf8mb4 / utf8mb4_unicode_ci (full emoji + unicode support)
-- Engine:  InnoDB (ACID, foreign-key enforcement)
-- IDs:     CHAR(36) UUIDs (binary-safe, generated by the application layer)
-- Money:   BIGINT unsigned whole coins/pips (no floating point)
-- Time:    DATETIME(6) UTC timestamps with microsecond precision
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------------------------------------------------------
-- users — authentication identities (profiles are 1:1 in `profiles`)
-- ----------------------------------------------------------------------------
CREATE TABLE users (
  id                  CHAR(36)      NOT NULL,
  phone               VARCHAR(20)   NULL,
  phone_normalized    VARCHAR(255)  NULL,
  email               VARCHAR(255)  NULL,
  password_hash       VARCHAR(255)  NULL,
  primary_provider    ENUM('phone','email') NOT NULL DEFAULT 'phone',
  status              ENUM('active','suspended','banned','deleted') NOT NULL DEFAULT 'active',
  role                VARCHAR(16)   NOT NULL DEFAULT 'player',  -- platform role (moderation access); also added by migration 1730000000000 on upgraded DBs
  is_verified         TINYINT(1)    NOT NULL DEFAULT 0,
  is_bot              TINYINT(1)    NOT NULL DEFAULT 0,  -- INTERNAL: never exposed to clients
  gender              ENUM('male','female','other','unspecified') NOT NULL DEFAULT 'unspecified',
  locale              VARCHAR(32)   NULL,
  date_of_birth       DATE          NULL,
  presence            ENUM('offline','online','in_game','away') NOT NULL DEFAULT 'offline',
  last_seen_at        DATETIME(6)   NULL,
  created_at          DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at          DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at          DATETIME(6)   NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_phone (phone),
  UNIQUE KEY uq_users_phone_normalized (phone_normalized),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_status (status),
  KEY idx_users_is_bot (is_bot),
  KEY idx_users_presence (presence),
  CONSTRAINT chk_users_phone_or_identity CHECK (
    phone IS NOT NULL OR email IS NOT NULL
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- profiles — public profile, wallet and aggregate stats (1:1 with users)
-- ----------------------------------------------------------------------------
CREATE TABLE profiles (
  user_id         CHAR(36)     NOT NULL,
  username        VARCHAR(32)  NOT NULL,
  display_name    VARCHAR(64)  NOT NULL,
  avatar_url      VARCHAR(512) NULL,
  country         VARCHAR(32)  NULL,
  bio             VARCHAR(512) NULL,
  level           INT          NOT NULL DEFAULT 1,
  xp              INT          NOT NULL DEFAULT 0,
  coins           BIGINT       NOT NULL DEFAULT 0,
  pips            BIGINT       NOT NULL DEFAULT 0,
  games_played    INT          NOT NULL DEFAULT 0,
  games_won       INT          NOT NULL DEFAULT 0,
  games_lost      INT          NOT NULL DEFAULT 0,
  games_drawn     INT          NOT NULL DEFAULT 0,
  streak_days     INT          NOT NULL DEFAULT 0,
  gifts_sent      INT          NOT NULL DEFAULT 0,
  gifts_received  INT          NOT NULL DEFAULT 0,
  equipped_frame_id       VARCHAR(36) NULL,
  equipped_banner_id      VARCHAR(36) NULL,
  equipped_chat_bubble_id VARCHAR(36) NULL,
  equipped_theme_id       VARCHAR(36) NULL,
  equipped_id_color_id    VARCHAR(36) NULL,
  active_title    VARCHAR(64)  NULL,
  unlocked_titles JSON         NULL,
  badges          JSON         NULL,
  settings        JSON         NULL,
  created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (user_id),
  UNIQUE KEY uq_profiles_username (username),
  KEY idx_profiles_level (level),
  KEY idx_profiles_country (country),
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_profiles_wallet CHECK (coins >= 0 AND pips >= 0),
  CONSTRAINT chk_profiles_stats CHECK (
    games_won + games_lost + games_drawn <= games_played
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- refresh_tokens — rotating refresh-token families (only hashes stored)
-- ----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
  id            CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  token_hash    CHAR(64)     NOT NULL,
  family_id     CHAR(36)     NOT NULL,
  expires_at    DATETIME(6)  NOT NULL,
  rotated_at    DATETIME(6)  NULL,
  revoked_at    DATETIME(6)  NULL,
  reused        TINYINT(1)   NOT NULL DEFAULT 0,
  ip_address    VARCHAR(45)  NULL,
  user_agent    VARCHAR(512) NULL,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_refresh_token_hash (token_hash),
  KEY idx_refresh_tokens_user (user_id),
  KEY idx_refresh_tokens_family (family_id),
  KEY idx_refresh_tokens_expires (expires_at),
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- otp_codes — SMS one-time passcodes (hashed, short-lived, attempt-bounded)
-- ----------------------------------------------------------------------------
CREATE TABLE otp_codes (
  id            CHAR(36)     NOT NULL,
  phone         VARCHAR(20)  NOT NULL,
  purpose       ENUM('login','verify_phone','reset') NOT NULL DEFAULT 'login',
  code_hash     CHAR(64)     NOT NULL,
  expires_at    DATETIME(6)  NOT NULL,
  attempts      INT          NOT NULL DEFAULT 0,
  max_attempts  INT          NOT NULL DEFAULT 5,
  consumed_at   DATETIME(6)  NULL,
  last_sent_at  DATETIME(6)  NOT NULL,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_otp_phone (phone),
  KEY idx_otp_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- friendships — directed friend edges (requests, friendships, blocks)
-- ----------------------------------------------------------------------------
CREATE TABLE friendships (
  id             CHAR(36)     NOT NULL,
  requester_id   CHAR(36)     NOT NULL,
  addressee_id   CHAR(36)     NOT NULL,
  status         ENUM('pending','accepted','blocked') NOT NULL DEFAULT 'pending',
  accepted_at    DATETIME(6)  NULL,
  created_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_friendship_pair (requester_id, addressee_id),
  KEY idx_friendships_requester (requester_id),
  KEY idx_friendships_addressee (addressee_id),
  KEY idx_friendships_status (status),
  CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_friendships_addressee FOREIGN KEY (addressee_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_friendships_not_self CHECK (requester_id <> addressee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- groups — friend groups / clubs
-- ----------------------------------------------------------------------------
CREATE TABLE groups (
  id            CHAR(36)     NOT NULL,
  name          VARCHAR(100) NOT NULL,
  avatar_url    VARCHAR(512) NULL,
  description   VARCHAR(512) NULL,
  owner_id      CHAR(36)     NOT NULL,
  chat_id       CHAR(36)     NULL,
  member_count  INT          NOT NULL DEFAULT 1,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_groups_owner (owner_id),
  KEY idx_groups_chat (chat_id),
  CONSTRAINT fk_groups_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_groups_chat FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE group_members (
  id            CHAR(36)     NOT NULL,
  group_id      CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  role          ENUM('owner','admin','member') NOT NULL DEFAULT 'member',
  last_read_at  DATETIME(6)  NULL,
  joined_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_group_member (group_id, user_id),
  KEY idx_group_members_group (group_id),
  KEY idx_group_members_user (user_id),
  CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
  CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- games — catalogue of playable table games
-- ----------------------------------------------------------------------------
CREATE TABLE games (
  id                    CHAR(36)     NOT NULL,
  slug                  VARCHAR(64)  NOT NULL,
  name                  VARCHAR(128) NOT NULL,
  description           VARCHAR(512) NULL,
  icon_url              VARCHAR(512) NULL,
  min_players           INT          NOT NULL DEFAULT 2,
  max_players           INT          NOT NULL DEFAULT 2,
  avg_duration_minutes  INT          NOT NULL DEFAULT 15,
  supports_bots         TINYINT(1)   NOT NULL DEFAULT 1,
  ranked_enabled        TINYINT(1)   NOT NULL DEFAULT 1,
  status                ENUM('active','inactive','maintenance','coming_soon') NOT NULL DEFAULT 'active',
  created_at            DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at            DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_games_slug (slug),
  KEY idx_games_status (status),
  CONSTRAINT chk_games_players CHECK (min_players >= 1 AND max_players >= min_players)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- rooms — lobbies / tables
-- ----------------------------------------------------------------------------
CREATE TABLE rooms (
  id             CHAR(36)     NOT NULL,
  game_id        CHAR(36)     NOT NULL,
  host_id        CHAR(36)     NOT NULL,
  name           VARCHAR(128) NULL,
  access_code    VARCHAR(64)  NULL,
  is_private     TINYINT(1)   NOT NULL DEFAULT 0,
  is_ranked      TINYINT(1)   NOT NULL DEFAULT 0,
  entry_fee_coins BIGINT      NOT NULL DEFAULT 0,
  max_players    INT          NOT NULL DEFAULT 2,
  status         ENUM('waiting','playing','finished','cancelled') NOT NULL DEFAULT 'waiting',
  settings       JSON         NULL,
  started_at     DATETIME(6)  NULL,
  ended_at       DATETIME(6)  NULL,
  created_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_rooms_game (game_id),
  KEY idx_rooms_host (host_id),
  KEY idx_rooms_status (status),
  KEY idx_rooms_access_code (access_code),
  CONSTRAINT fk_rooms_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE RESTRICT,
  CONSTRAINT fk_rooms_host FOREIGN KEY (host_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_rooms_fee CHECK (entry_fee_coins >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE room_players (
  id           CHAR(36)     NOT NULL,
  room_id      CHAR(36)     NOT NULL,
  user_id      CHAR(36)     NOT NULL,
  seat_number  INT          NOT NULL DEFAULT 0,
  is_bot       TINYINT(1)   NOT NULL DEFAULT 0,
  is_ready     TINYINT(1)   NOT NULL DEFAULT 0,
  status       ENUM('invited','joined','ready','left','kicked') NOT NULL DEFAULT 'invited',
  joined_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_room_player (room_id, user_id),
  KEY idx_room_players_room (room_id),
  KEY idx_room_players_user (user_id),
  CONSTRAINT fk_room_players_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
  CONSTRAINT fk_room_players_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- seasons — competitive seasons (rankings are scoped per season + game)
-- ----------------------------------------------------------------------------
CREATE TABLE seasons (
  id             CHAR(36)     NOT NULL,
  name           VARCHAR(64)  NOT NULL,
  season_number  INT          NOT NULL,
  starts_at      DATETIME(6)  NOT NULL,
  ends_at        DATETIME(6)  NOT NULL,
  status         ENUM('upcoming','active','completed') NOT NULL DEFAULT 'upcoming',
  rewards        JSON         NULL,
  created_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_seasons_number (season_number),
  KEY idx_seasons_status (status),
  CONSTRAINT chk_seasons_dates CHECK (ends_at > starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- matches — completed / in-progress game instances
-- ----------------------------------------------------------------------------
CREATE TABLE matches (
  id               CHAR(36)     NOT NULL,
  game_id          CHAR(36)     NOT NULL,
  room_id          CHAR(36)     NULL,
  season_id        CHAR(36)     NULL,
  is_ranked        TINYINT(1)   NOT NULL DEFAULT 0,
  entry_fee_coins  BIGINT       NOT NULL DEFAULT 0,
  status           ENUM('pending','in_progress','completed','abandoned','cancelled') NOT NULL DEFAULT 'pending',
  results          JSON         NULL,
  replay_data      JSON         NULL,
  duration_seconds INT          NULL,
  started_at       DATETIME(6)  NULL,
  finished_at      DATETIME(6)  NULL,
  created_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_matches_game (game_id),
  KEY idx_matches_room (room_id),
  KEY idx_matches_season (season_id),
  KEY idx_matches_status (status),
  KEY idx_matches_created (created_at),
  CONSTRAINT fk_matches_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE RESTRICT,
  CONSTRAINT fk_matches_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE SET NULL,
  CONSTRAINT fk_matches_season FOREIGN KEY (season_id) REFERENCES seasons (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE match_players (
  id            CHAR(36)     NOT NULL,
  match_id      CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  seat_number   INT          NOT NULL DEFAULT 0,
  placement     INT          NULL,
  score         INT          NOT NULL DEFAULT 0,
  result        ENUM('win','loss','draw','abandoned') NOT NULL DEFAULT 'abandoned',
  rating_delta  INT          NOT NULL DEFAULT 0,
  coins_delta   BIGINT       NOT NULL DEFAULT 0,
  is_bot        TINYINT(1)   NOT NULL DEFAULT 0,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_match_player (match_id, user_id),
  KEY idx_match_players_match (match_id),
  KEY idx_match_players_user (user_id),
  CONSTRAINT fk_match_players_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
  CONSTRAINT fk_match_players_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- rankings — per (season, game, user) rating rows; leaderboard source
-- ----------------------------------------------------------------------------
CREATE TABLE rankings (
  id              CHAR(36)    NOT NULL,
  season_id       CHAR(36)    NOT NULL,
  game_id         CHAR(36)    NOT NULL,
  user_id         CHAR(36)    NOT NULL,
  rating          INT         NOT NULL DEFAULT 1000,
  peak_rating     INT         NOT NULL DEFAULT 1000,
  wins            INT         NOT NULL DEFAULT 0,
  losses          INT         NOT NULL DEFAULT 0,
  draws           INT         NOT NULL DEFAULT 0,
  matches_played  INT         NOT NULL DEFAULT 0,
  rank_position   INT         NULL,
  final_tier      VARCHAR(16) NULL,
  rewards_granted TINYINT(1)  NOT NULL DEFAULT 0,
  created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_ranking_row (season_id, game_id, user_id),
  KEY idx_ranking_leaderboard (season_id, game_id, rating),
  KEY idx_rankings_user (user_id),
  CONSTRAINT fk_rankings_season FOREIGN KEY (season_id) REFERENCES seasons (id) ON DELETE CASCADE,
  CONSTRAINT fk_rankings_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE,
  CONSTRAINT fk_rankings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- season_reward_claims — idempotent record of granted season rewards
-- (one tier claim per player per season; one game claim per season+game)
-- ----------------------------------------------------------------------------
CREATE TABLE season_reward_claims (
  id             CHAR(36)    NOT NULL,
  season_id      CHAR(36)    NOT NULL,
  user_id        CHAR(36)    NOT NULL,
  kind           ENUM('tier','game') NOT NULL DEFAULT 'tier',
  game_id        CHAR(36)    NULL,
  rank_achieved  INT         NOT NULL DEFAULT 0,
  tier           VARCHAR(16) NOT NULL DEFAULT 'bronze',
  coins_granted  BIGINT      NOT NULL DEFAULT 0,
  pips_granted   BIGINT      NOT NULL DEFAULT 0,
  xp_granted     BIGINT      NOT NULL DEFAULT 0,
  granted_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_season_claim (season_id, user_id, kind, game_id),
  KEY idx_season_claim_season (season_id),
  KEY idx_season_claim_user (user_id),
  CONSTRAINT fk_season_claim_season FOREIGN KEY (season_id) REFERENCES seasons (id) ON DELETE CASCADE,
  CONSTRAINT fk_season_claim_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_season_claim_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- shop_items — purchasable cosmetics / consumables
-- ----------------------------------------------------------------------------
CREATE TABLE shop_items (
  id               CHAR(36)     NOT NULL,
  name             VARCHAR(100) NOT NULL,
  description      VARCHAR(512) NULL,
  type             ENUM('avatar_frame','banner','chat_bubble','theme','game_skin','game_piece','board_theme','id_color','username_change','dice_set','emote','bundle','consumable') NOT NULL,
  rarity           ENUM('common','rare','epic','legendary') NOT NULL DEFAULT 'common',
  image_url        VARCHAR(512) NULL,
  price            BIGINT       NOT NULL DEFAULT 0,
  currency         ENUM('coins','pips') NOT NULL DEFAULT 'coins',
  discount_percent INT          NOT NULL DEFAULT 0,
  is_unique_owned  TINYINT(1)   NOT NULL DEFAULT 1,
  giftable         TINYINT(1)   NOT NULL DEFAULT 1,
  is_available     TINYINT(1)   NOT NULL DEFAULT 1,
  stock            INT          NOT NULL DEFAULT 0,
  sort_order       INT          NOT NULL DEFAULT 0,
  metadata         JSON         NULL,
  created_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at       DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_shop_items_type (type),
  KEY idx_shop_items_available (is_available),
  CONSTRAINT chk_shop_items_price CHECK (price >= 0 AND discount_percent BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- user_inventory — owned items (unique items: 1 row; consumables: quantity)
-- Note: partial unique index is emulated by the application transaction;
--       a generated column keeps unique items one-per-user at the DB level.
-- ----------------------------------------------------------------------------
CREATE TABLE user_inventory (
  id               CHAR(36)     NOT NULL,
  user_id          CHAR(36)     NOT NULL,
  item_id          CHAR(36)     NOT NULL,
  quantity         INT          NOT NULL DEFAULT 1,
  is_equipped      TINYINT(1)   NOT NULL DEFAULT 0,
  is_unique_owned  TINYINT(1)   NOT NULL DEFAULT 1,
  source           ENUM('purchase','gift') NOT NULL DEFAULT 'purchase',
  gifted_by_id     CHAR(36)     NULL,
  unique_key       CHAR(72)     GENERATED ALWAYS AS
                     (IF(is_unique_owned = 1, CONCAT(user_id, ':', item_id), NULL)) STORED,
  expires_at       DATETIME(6)  NULL,
  acquired_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_inventory_unique_item (unique_key),
  KEY idx_inventory_user (user_id),
  KEY idx_inventory_item (item_id),
  KEY idx_inventory_gifted_by (gifted_by_id),
  CONSTRAINT fk_inventory_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_item FOREIGN KEY (item_id) REFERENCES shop_items (id) ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_gifted_by FOREIGN KEY (gifted_by_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT chk_inventory_quantity CHECK (quantity >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- transactions — immutable wallet ledger
-- ----------------------------------------------------------------------------
CREATE TABLE transactions (
  id              CHAR(36)     NOT NULL,
  user_id         CHAR(36)     NOT NULL,
  type            ENUM('purchase','reward','gift','gift_purchase','refund','admin_adjustment','match_payout','daily_reward','quest_reward','season_reward') NOT NULL,
  currency        ENUM('coins','pips') NOT NULL,
  amount          BIGINT       NOT NULL,
  balance_after   BIGINT       NOT NULL DEFAULT 0,
  reference_type  VARCHAR(128) NULL,
  reference_id    CHAR(36)     NULL,
  description     VARCHAR(255) NULL,
  created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_transactions_user_created (user_id, created_at),
  KEY idx_transactions_type (type),
  KEY idx_transactions_reference (reference_type, reference_id),
  CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- chats / chat_participants / messages / message_reads
-- ----------------------------------------------------------------------------
CREATE TABLE chats (
  id                CHAR(36)     NOT NULL,
  type              ENUM('direct','group','room','lounge','system') NOT NULL,
  title             VARCHAR(128) NULL,
  avatar_url        VARCHAR(512) NULL,
  context_id        CHAR(36)     NULL,  -- groups.id or rooms.id
  access_pass       VARCHAR(64)  NULL,  -- Chat Pass code (NULL = open)
  theme_key         VARCHAR(32)  NULL,  -- per-chat bubble/theme style
  is_public         TINYINT(1)   NOT NULL DEFAULT 0,
  last_message_id   CHAR(36)     NULL,
  pinned_message_id CHAR(36)     NULL,
  last_message_at   DATETIME(6)  NULL,
  created_at        DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_chats_type (type),
  KEY idx_chats_context (context_id),
  KEY idx_chats_public (is_public),
  KEY idx_chats_last_message (last_message_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE chat_participants (
  id           CHAR(36)     NOT NULL,
  chat_id      CHAR(36)     NOT NULL,
  user_id      CHAR(36)     NOT NULL,
  role         ENUM('owner','admin','member') NOT NULL DEFAULT 'member',
  is_muted     TINYINT(1)   NOT NULL DEFAULT 0,
  last_read_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  joined_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_chat_participant (chat_id, user_id),
  KEY idx_chat_participants_chat (chat_id),
  KEY idx_chat_participants_user (user_id),
  CONSTRAINT fk_chat_participants_chat FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_participants_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE messages (
  id           CHAR(36)     NOT NULL,
  chat_id      CHAR(36)     NOT NULL,
  sender_id    CHAR(36)     NOT NULL,
  type         ENUM('text','image','system','game_invite','emote','voice','pinned') NOT NULL DEFAULT 'text',
  body         TEXT         NOT NULL,
  metadata     JSON         NULL,
  reply_to_id  CHAR(36)     NULL,
  is_pinned    TINYINT(1)   NOT NULL DEFAULT 0,
  pinned_at    DATETIME(6)  NULL,
  pinned_by    CHAR(36)     NULL,
  edited_at    DATETIME(6)  NULL,
  deleted_at   DATETIME(6)  NULL,
  created_at   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_messages_chat_created (chat_id, created_at),
  KEY idx_messages_sender (sender_id),
  KEY idx_messages_reply (reply_to_id),
  KEY idx_messages_pinned (chat_id, is_pinned),
  CONSTRAINT fk_messages_chat FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_reply FOREIGN KEY (reply_to_id) REFERENCES messages (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- last_message / pinned self-references after both tables exist
ALTER TABLE chats
  ADD CONSTRAINT fk_chats_last_message FOREIGN KEY (last_message_id) REFERENCES messages (id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_chats_pinned_message FOREIGN KEY (pinned_message_id) REFERENCES messages (id) ON DELETE SET NULL;

-- Reactions on messages (one row per user + emoji)
CREATE TABLE message_reactions (
  id          CHAR(36)    NOT NULL,
  message_id  CHAR(36)    NOT NULL,
  user_id     CHAR(36)    NOT NULL,
  emoji       VARCHAR(16) NOT NULL,
  created_at  DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_reaction (message_id, user_id, emoji),
  KEY idx_reactions_message (message_id),
  KEY idx_reactions_user (user_id),
  CONSTRAINT fk_reactions_message FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE,
  CONSTRAINT fk_reactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Active voice-channel sessions (LiveKit roster); room name = voice:{chat_id}
CREATE TABLE voice_sessions (
  id             CHAR(36)    NOT NULL,
  chat_id        CHAR(36)    NOT NULL,
  user_id        CHAR(36)    NOT NULL,
  identity       VARCHAR(64) NOT NULL,
  is_muted       TINYINT(1)  NOT NULL DEFAULT 0,
  is_deafened    TINYINT(1)  NOT NULL DEFAULT 0,
  is_speaking    TINYINT(1)  NOT NULL DEFAULT 0,
  is_broadcasting TINYINT(1) NOT NULL DEFAULT 0,
  joined_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at     DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_voice_session (chat_id, user_id),
  KEY idx_voice_sessions_chat (chat_id),
  KEY idx_voice_sessions_user (user_id),
  CONSTRAINT fk_voice_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE message_reads (
  id          CHAR(36)     NOT NULL,
  message_id  CHAR(36)     NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  read_at     DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_message_read (message_id, user_id),
  KEY idx_message_reads_message (message_id),
  KEY idx_message_reads_user (user_id),
  CONSTRAINT fk_message_reads_message FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE,
  CONSTRAINT fk_message_reads_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- reports — user-submitted moderation reports
-- ----------------------------------------------------------------------------
CREATE TABLE reports (
  id              CHAR(36)     NOT NULL,
  reporter_id     CHAR(36)     NOT NULL,
  target_type     ENUM('user','message','room','group','chat','voice') NOT NULL,
  target_id       CHAR(36)     NOT NULL,
  reason          VARCHAR(128) NOT NULL,
  details         TEXT         NULL,
  status          ENUM('open','reviewing','resolved','dismissed') NOT NULL DEFAULT 'open',
  resolved_by     CHAR(36)     NULL,
  resolution_note TEXT         NULL,
  resolved_at     DATETIME(6)  NULL,
  created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_reports_reporter (reporter_id),
  KEY idx_reports_target (target_type, target_id),
  KEY idx_reports_status (status),
  CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_reports_resolver FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- bans — enforcement actions
-- ----------------------------------------------------------------------------
CREATE TABLE bans (
  id          CHAR(36)     NOT NULL,
  user_id     CHAR(36)     NOT NULL,
  type        ENUM('chat','login','matchmaking','permanent') NOT NULL,
  reason      VARCHAR(255) NULL,
  banned_by   CHAR(36)     NULL,
  expires_at  DATETIME(6)  NULL,
  lifted_at   DATETIME(6)  NULL,
  created_at  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_bans_user (user_id),
  KEY idx_bans_active (user_id, type, expires_at),
  CONSTRAINT fk_bans_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_bans_banner FOREIGN KEY (banned_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- bots — internal AI player configuration (1:1 with bot users)
-- ----------------------------------------------------------------------------
CREATE TABLE bots (
  user_id     CHAR(36)     NOT NULL,
  difficulty  ENUM('easy','medium','hard','expert') NOT NULL DEFAULT 'medium',
  personality VARCHAR(64)  NULL,
  config      JSON         NULL,
  is_active   TINYINT(1)   NOT NULL DEFAULT 1,
  created_at  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (user_id),
  KEY idx_bots_difficulty (difficulty),
  KEY idx_bots_active (is_active),
  CONSTRAINT fk_bots_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- quests — catalogue of repeatable daily quests
-- ----------------------------------------------------------------------------
CREATE TABLE quests (
  id              CHAR(36)     NOT NULL,
  code            VARCHAR(64)  NOT NULL,
  name            VARCHAR(128) NOT NULL,
  description     VARCHAR(512) NULL,
  goal_type       ENUM('login','play_match','win_match','play_with_friends','send_gift') NOT NULL,
  goal_target     INT          NOT NULL DEFAULT 1,
  reward_coins    BIGINT       NOT NULL DEFAULT 0,
  reward_pips     BIGINT       NOT NULL DEFAULT 0,
  reward_xp       INT          NOT NULL DEFAULT 0,
  reward_currency ENUM('coins','pips') NOT NULL DEFAULT 'coins',
  sort_order      INT          NOT NULL DEFAULT 1,
  is_active       TINYINT(1)   NOT NULL DEFAULT 1,
  created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_quests_code (code),
  KEY idx_quests_goal (goal_type),
  KEY idx_quests_active (is_active),
  CONSTRAINT chk_quests_target CHECK (goal_target >= 1),
  CONSTRAINT chk_quests_rewards CHECK (reward_coins >= 0 AND reward_pips >= 0 AND reward_xp >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- user_quests — one row per user per quest per day (progress + claim state)
-- ----------------------------------------------------------------------------
CREATE TABLE user_quests (
  id            CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  quest_id      CHAR(36)     NOT NULL,
  day           DATE         NOT NULL,
  progress      INT          NOT NULL DEFAULT 0,
  goal_target   INT          NOT NULL DEFAULT 1,
  status        ENUM('in_progress','claimable','claimed','expired') NOT NULL DEFAULT 'in_progress',
  completed_at  DATETIME(6)  NULL,
  claimed_at    DATETIME(6)  NULL,
  created_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_quest_day (user_id, quest_id, day),
  KEY idx_user_quests_user (user_id),
  KEY idx_user_quests_quest (quest_id),
  KEY idx_user_quests_day (day),
  CONSTRAINT fk_user_quests_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_quests_quest FOREIGN KEY (quest_id) REFERENCES quests (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------------
-- daily_reward_claims — free daily login reward ledger (one claim/user/day)
-- ----------------------------------------------------------------------------
CREATE TABLE daily_reward_claims (
  id            CHAR(36)     NOT NULL,
  user_id       CHAR(36)     NOT NULL,
  day           DATE         NOT NULL,
  streak_day    INT          NOT NULL DEFAULT 1,
  coins_awarded BIGINT       NOT NULL DEFAULT 0,
  pips_awarded  BIGINT       NOT NULL DEFAULT 0,
  claimed_at    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_daily_reward_day (user_id, day),
  KEY idx_daily_rewards_user (user_id),
  KEY idx_daily_rewards_day (day),
  CONSTRAINT fk_daily_rewards_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
